from typing import List
from datetime import datetime, timezone
import logging

from app.ingestion.base import JobSource, RawJob


logger = logging.getLogger(__name__)


class SandboxAdapter(JobSource):
    """Controlled JobPulse sandbox that generates deterministic test jobs."""

    def __init__(
        self,
        source_id: int,
        source_name: str,
        sandbox_url: str = "",
    ):
        super().__init__(source_id, source_name)
        self.sandbox_url = sandbox_url

    async def fetch(self) -> List[RawJob]:
        """Generate controlled test jobs without an external service."""

        logger.info(
            f"[{self.source_name}] Generating sandbox test jobs"
        )

        now = datetime.now(timezone.utc)

        jobs = [
            RawJob(
                title="Sandbox Python Developer",
                company="JobPulse Demo",
                location="Remote",
                description=(
                    "Test job generated by the JobPulse sandbox. "
                    "This demonstrates the complete ingestion pipeline."
                ),
                url="https://example.com/jobs/sandbox-python-developer",
                job_type="FULL_TIME",
                published_at=now,
                external_id="sandbox-python-developer-001",
            ),
            RawJob(
                title="Sandbox Frontend Engineer",
                company="JobPulse Demo",
                location="Remote",
                description=(
                    "Controlled frontend engineering test listing "
                    "used to demonstrate sandbox ingestion."
                ),
                url="https://example.com/jobs/sandbox-frontend-engineer",
                job_type="FULL_TIME",
                published_at=now,
                external_id="sandbox-frontend-engineer-002",
            ),
            RawJob(
                title="Sandbox Backend Engineer",
                company="JobPulse Demo",
                location="India",
                description=(
                    "Controlled backend engineering test listing "
                    "for validating JobPulse ingestion."
                ),
                url="https://example.com/jobs/sandbox-backend-engineer",
                job_type="FULL_TIME",
                published_at=now,
                external_id="sandbox-backend-engineer-003",
            ),
            RawJob(
                title="Sandbox Data Analyst",
                company="JobPulse Demo",
                location="Remote",
                description=(
                    "Test data analyst position generated by "
                    "the JobPulse sandbox source."
                ),
                url="https://example.com/jobs/sandbox-data-analyst",
                job_type="FULL_TIME",
                published_at=now,
                external_id="sandbox-data-analyst-004",
            ),
            RawJob(
                title="Sandbox DevOps Engineer",
                company="JobPulse Demo",
                location="Remote",
                description=(
                    "Controlled DevOps test listing used to "
                    "verify validation and deduplication."
                ),
                url="https://example.com/jobs/sandbox-devops-engineer",
                job_type="CONTRACT",
                published_at=now,
                external_id="sandbox-devops-engineer-005",
            ),
        ]

        logger.info(
            f"[{self.source_name}] Generated {len(jobs)} sandbox jobs"
        )

        return jobs